CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE assignments (id TEXT PRIMARY KEY, student TEXT NOT NULL, subject TEXT NOT NULL, title TEXT NOT NULL, due TEXT, done INTEGER NOT NULL DEFAULT 0);
