// Schedule storage and school-site import helpers.
const LABELS={ela:'Language Arts',math:'Math',science:'Science',social:'Social Studies',stem:'STEM',tech:'Technology'};
const state={view:null,assignments:null,schedules:{leon:[],logan:[]},scheduledDays:{leon:{},logan:{}},scheduleDates:{leon:'',logan:''},displayCards:{leon:[],logan:[],monitor:[]},scheduleMessage:'',showEditor:false,auth:null};
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const SCHOOL_LINKS={
  star:['Star Store','https://www.reachattendancerewards.org/'],
  horizon:['Horizon','https://horizon.reachcyber.org/events/?year=2026&month=10&registration=Open&my_students=1'],
  support:['Support Portal','https://login.microsoftonline.com/d2700aef-1433-4902-aa8f-3ac82615f2d9/saml2?SAMLRequest=fZJBi9swEIX%2Fim86yZYU20lEHDAJhcC2lGzbQy%2FLRB5vBLKUauRu99%2FXdli6PbRXvfe%2BN8xoRzC4m27HdPVn%2FDEipawlwphs8IfgaRwwPmL8aQ1%2BPT807JrSjXRRRARzNa8XjPmEAA%2FPmJswFDOvOM%2FiYRZZdpyQ1sPM%2B5N24dn6fLAmBgp9Ct5Zf893ai0EYM9luVrxcisUB9j0fAVmo2pZ9arbLiWKZadjw56MFAbFpeLrTSl5KTeGgzEXrrBco%2Bi3dV2Vk5VoxJOnBD41TAlVcym4UF%2BU1FWtq%2FI7y75hpGVKlQuW%2FRqcJz03NWyMXgcgS9rDgKST0Y%2Ftxwc9GTW8bet95Pb%2FzC2GFExwbL%2Bb3XqZLu4pOIgv1nc0r2JXvNd290N9mlin4%2BfgrHnNWufCy2G6RMKGpTgiyz6EOED6d7vM5fJiO94vVo0DWNd2XUQiVuzvrX%2F%2FiP1v&RelayState=EOd9iVT5dAgRun7wcqEyTE%252FFN%252BQ610lfmzkupB9i3cFReSkTrfyQh%252B8iQIbx%250AJYKG%250A'],
  focus:['Focus Parent Portal','https://rccs.focusschoolsoftware.com/focus/Modules.php?force_package=SIS&modname=misc/Portal.php']
};
function copySchedule(items){return JSON.parse(JSON.stringify(items||[]))}
function loadSchedules(raw){for(const student of ['leon','logan']){const stored=raw?.[student],days={...(stored?.days||{})};if(stored?.date&&Array.isArray(stored.today))days[stored.date]=stored.today;state.scheduledDays[student]=cleanScheduledDays(days);state.scheduleDates[student]=scheduleDay();state.schedules[student]=scheduleFor(student)}}
function schedulePayload(){return Object.fromEntries(['leon','logan'].map(student=>[student,{days:cleanScheduledDays(state.scheduledDays[student])}]))}
function loadCards(raw){const defaults={leon:['🎯 Focus on today','📚 One class at a time','💧 Take a water break','⭐ You’ve got this'],logan:['🎯 Focus on today','📚 One class at a time','💧 Take a water break','⭐ You’ve got this'],monitor:['🌅 Start strong','🍎 Lunch at noon','📚 Check due work','✅ Celebrate progress']};for(const scope of ['leon','logan','monitor'])state.displayCards[scope]=Array.from({length:4},(_,i)=>String(raw?.[scope]?.[i]??defaults[scope][i]))}
function selectScheduleDate(date){const student=state.editorStudent||'leon';state.scheduleDates[student]=date||scheduleDay();state.schedules[student]=scheduleFor(student,state.scheduleDates[student]);state.scheduleMessage=state.scheduledDays[student]?.[state.scheduleDates[student]]?'Loaded saved day':'No schedule saved for this day';refreshScheduleEditor()}
function commitOpenSchedule(){const student=state.editorStudent||'leon',date=state.scheduleDates[student]||scheduleDay();state.scheduledDays[student][date]=copySchedule(state.schedules[student])}
function removeScheduleEntry(index){const student=state.editorStudent||'leon';state.schedules[student].splice(index,1);state.scheduleMessage='Unsaved changes';refreshScheduleEditor()}
function saveOpenSchedule(){const student=state.editorStudent||'leon',date=state.scheduleDates[student]||scheduleDay();commitOpenSchedule();state.scheduleMessage='Saved this day';return saveScheduleChanges(student,date)}
function clearOpenSchedule(){const student=state.editorStudent||'leon';state.schedules[student]=[];state.scheduleMessage='Unsaved changes';refreshScheduleEditor()}
function importModal(){return document.getElementById('import-modal')}function closeImport(){importModal()?.remove()}function normalizeTitle(value){return String(value).replace(/\*/g,'').replace(/\s+/g,' ').trim().toLowerCase()}function parsePastedAssignments(text){const lines=text.replace(/&#x9;/g,' ').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),dateLine=/^(?:Sun|Mon|Tue|Wed|Thu|Fri|Sat),\s+[A-Z][a-z]{2}\s+\d{1,2},\s+\d{4},\s+\d{1,2}:\d{2}\s*(?:AM|PM)?$/;let title='',items=[];for(const line of lines){if(dateLine.test(line)){if(title){const d=new Date(line.replace(/,\s+\d{1,2}:\d{2}.*$/,''));if(!isNaN(d))items.push({title,due:d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')})}title='';continue}if(/^(Submitted|Late |Assignments|Assignment Group|Score|Total:|Totals |View feedback|Out of |—|\d+ pts)/i.test(line))continue;if(!/^Brady |^Assignment\s+Due Date/i.test(line))title=line}return [...new Map(items.map(x=>[`${normalizeTitle(x.title)}|${x.due}`,x])).values()]}
function openImport(){const student=state.editorStudent||'leon',subject=state.editorSubject;document.body.insertAdjacentHTML('beforeend',`<section id="import-modal" class="import-modal"><div class="import-box"><button class="button light" onclick="closeImport()">Close</button><h2>Import ${student==='leon'?'Leon':'Logan'}’s ${LABELS[subject]||subject} assignments</h2><p class="small">Paste the assignment list from the school site. Submitted dates, scores, and feedback are ignored.</p><textarea id="import-text" placeholder="Paste assignments here"></textarea><div class="actions"><button class="button" onclick="previewImport()">Preview import</button></div><div id="import-preview"></div></div></section>`)}
function previewImport(){const student=state.editorStudent||'leon',subject=state.editorSubject,parsed=parsePastedAssignments(document.getElementById('import-text').value),existing=state.assignments[student][subject],rows=parsed.map(item=>{const match=existing.find(x=>normalizeTitle(x.title)===normalizeTitle(item.title));return {...item,status:!match?'new':!match.due?'add-date':match.due===item.due?'unchanged':'review',id:match?.id}});state.importRows=rows;document.getElementById('import-preview').innerHTML=`<h3>Preview</h3><p class="small">${rows.filter(x=>x.status==='new').length} new · ${rows.filter(x=>x.status==='add-date').length} dates to add · ${rows.filter(x=>x.status==='unchanged').length} unchanged · ${rows.filter(x=>x.status==='review').length} date changes to review</p>${rows.map(x=>`<div class="import-row ${x.status}"><strong>${esc(x.title)}</strong><span>${x.due} · ${x.status.replace('-',' ')}</span></div>`).join('')}<div class="actions"><button class="button" onclick="applyImport()">Apply new items and missing dates</button></div>`}
async function applyImport(){const student=state.editorStudent||'leon',subject=state.editorSubject;for(const row of state.importRows||[]){if(row.status==='new'){const x={id:crypto.randomUUID?.()||Date.now().toString()+Math.random(),title:row.title,due:row.due,done:false};state.assignments[student][subject].push(x);await saveAssignmentChange('add',{student,subject,x})}if(row.status==='add-date'){const found=findTask(row.id);found.x.due=row.due;await saveAssignmentChange('update',found)}}closeImport();editor()}
function closeScheduleImport(){document.getElementById('schedule-import-modal')?.remove()}
function openScheduleImport(){const student=state.editorStudent||'leon',studentNote=student==='leon'?'Leon’s Language Arts, Math, Science, Social Studies, STEM, and Spanish classes, plus Monday/Wednesday Physical Education':'Logan’s Language Arts, Math, Science, Social Studies, and Spanish classes, plus Tuesday/Thursday Art and Monday/Wednesday Ed Tech';closeScheduleEditor();document.body.insertAdjacentHTML('beforeend',`<section id="schedule-import-modal" class="import-modal"><div class="import-box"><button class="button light" onclick="closeScheduleImport()">Close</button><h2>Import several schedule days</h2><p class="small">Paste the calendar copied from the class site. The preview keeps ${studentNote}, removes conflicts, and adds lunch.</p><textarea id="schedule-import-text" placeholder="Paste the class calendar here"></textarea><div class="actions"><button class="button" onclick="previewScheduleImport()">Build schedule preview</button></div><div id="schedule-import-preview"></div></div></section>`)}
function calendarISO(label){const now=new Date(),parsed=new Date(`${label}, ${now.getFullYear()} 12:00:00`);if(isNaN(parsed))return'';if(parsed<new Date(now.getTime()-120*86400000))parsed.setFullYear(parsed.getFullYear()+1);return `${parsed.getFullYear()}-${String(parsed.getMonth()+1).padStart(2,'0')}-${String(parsed.getDate()).padStart(2,'0')}`}
function importedSubject(line){if(/(?:Brady ELA|Kochkodin ELA|English Language Arts 4)/i.test(line))return'ela';if(/(?:Brady Social Studies|Kochkodin Social Studies|Social Studies 4)/i.test(line))return'social';if(/\bSTEM\b/i.test(line))return'stem';if(/(?:Trimble Science|Smith-Science|Science with Ms\. Smith)/i.test(line))return'science';if(/(?:Trimble-? Math|Smith-Math|Math with Ms\. Smith)/i.test(line))return'math';if(/Physical Education/i.test(line))return'pe';if(/\b(?:Ed Tech|Educational Technology)\b/i.test(line))return'edtech';if(/\bArts?\b/i.test(line)&&!/(martial|language arts)/i.test(line))return'art';if(/Spanish/i.test(line)&&/(Wittie|Elementary Spanish)/i.test(line))return'spanish';return''}
function importedMinutes(value,ampm){let [h,m]=value.split(':').map(Number);if(ampm==='PM'&&h!==12)h+=12;if(ampm==='AM'&&h===12)h=0;return h*60+m}
function minutesTime(value){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function lunchSlot(items){for(let start=690;start<=750;start+=15)if(items.every(x=>start+30<=x.start||start>=x.end))return start;return null}
function chooseDailyClasses(candidates){const grouped={};for(const item of candidates)(grouped[item.subject]??=[]).push(item);const groups=Object.values(grouped),rank={pe:1,art:1,edtech:1};let best=[],bestScore=-Infinity;function visit(index,chosen){if(index===groups.length){const over=chosen.reduce((sum,x)=>sum+Math.max(0,x.end-840),0),finish=Math.max(0,...chosen.map(x=>x.end)),importance=chosen.reduce((sum,x)=>sum+(rank[x.subject]?1000:2000),0),score=chosen.length*100000+importance-over*100-finish;if(score>bestScore){bestScore=score;best=[...chosen]}return}visit(index+1,chosen);for(const item of groups[index])if(chosen.every(x=>item.start>=x.end||item.end<=x.start))visit(index+1,[...chosen,item])}visit(0,[]);return best.sort((a,b)=>a.start-b.start)}
function parseSchedulePaste(text,student=state.editorStudent||'leon'){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),days={},skipped=[];let date='',subject='';for(let i=0;i<lines.length;i++){const line=lines[i],dated=line.match(/^(?:Yesterday|Tomorrow|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),\s+(.+)$/i);if(dated){date=calendarISO(dated[1]);subject='';continue}if(/^T?oday$/i.test(line)&&lines[i+1]){date=calendarISO(lines[++i]);subject='';continue}const foundSubject=importedSubject(line);if(foundSubject){subject=foundSubject;continue}if(/(Family Mentor|Community Portal|My Career Journey)/i.test(line)){subject='';continue}const time=line.match(/^(\d{1,2}:\d{2})\s*(AM|PM)\s+to\s+(\d{1,2}:\d{2})\s*(AM|PM)$/i);if(!date||!subject||!time)continue;const title=lines[i-1]||'',optional=/(optional|office hours?|small group|club|mentor)/i.test(title),weekday=new Date(date+'T12:00:00').getDay(),allowedEncore=subject==='pe'?student==='leon'&&[1,3].includes(weekday):subject==='art'?student==='logan'&&[2,4].includes(weekday):subject==='edtech'?student==='logan'&&[1,3].includes(weekday):subject==='stem'?student==='leon':true;if(optional||!allowedEncore)continue;const start=importedMinutes(time[1],time[2].toUpperCase()),end=importedMinutes(time[3],time[4].toUpperCase());(days[date]??=[]).push({subject,title,start,end})}const output={};for(const [day,candidates] of Object.entries(days)){const chosen=chooseDailyClasses(candidates),selectedSubjects=new Set(chosen.map(x=>x.subject));for(const item of candidates)if(!selectedSubjects.has(item.subject))skipped.push({...item,date:day,reason:'time conflict'});const lunch=lunchSlot(chosen);if(lunch!==null)chosen.push({subject:'break',title:'Lunch',start:lunch,end:lunch+30});output[day]=chosen.sort((a,b)=>a.start-b.start).map(x=>({type:x.subject==='break'?'break':'class',subject:['spanish','pe','art','edtech','break'].includes(x.subject)?x.subject==='break'?'break':'custom':x.subject,label:x.subject==='spanish'?'Spanish':x.subject==='pe'?'Physical Education':x.subject==='art'?'Art':x.subject==='edtech'?'Ed Tech':x.title,time:minutesTime(x.start),endTime:minutesTime(x.end)}))}return{days:output,skipped}}
function previewScheduleImport(){const parsed=parseSchedulePaste(document.getElementById('schedule-import-text').value),dates=Object.keys(parsed.days).sort();state.scheduleImport=parsed;document.getElementById('schedule-import-preview').innerHTML=dates.length?`<h3>Preview</h3><p class="small">${dates.length} days found · ${parsed.skipped.length} conflicting class${parsed.skipped.length===1?'':'es'} omitted</p><div class="schedule-preview">${dates.map(date=>`<section class="due-class"><h3>${new Date(date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h3><div class="schedule-preview-day">${parsed.days[date].map(x=>`<div class="schedule-item ${x.type==='break'?'break':''}" style="${scheduleItemStyle(x)}"><span>${esc(scheduleLabel(x))}</span><time>${formatScheduleTime(x.time)}</time></div>`).join('')}</div></section>`).join('')}</div>${parsed.skipped.length?`<details><summary>See omitted conflicts</summary>${parsed.skipped.map(x=>`<p class="small">${esc(x.title)} on ${x.date} — ${x.reason}</p>`).join('')}</details>`:''}<div class="actions"><button class="button" onclick="applyScheduleImport()">Add these days</button></div>`:'<p class="notice">No primary live classes were found. Make sure the copied text includes the course names and meeting times.</p>'}
async function applyScheduleImport(){const student=state.editorStudent||'leon',parsed=state.scheduleImport;if(!parsed)return;for(const [date,items] of Object.entries(parsed.days)){state.scheduledDays[student][date]=copySchedule(items);await saveScheduleChanges(student,date)}state.scheduleDates[student]=Object.keys(parsed.days).sort()[0]||scheduleDay();state.schedules[student]=scheduleFor(student,state.scheduleDates[student]);state.scheduleMessage=`Imported ${Object.keys(parsed.days).length} schedule days`;closeScheduleImport();editor();openScheduleEditor()}
